# goose.toml
[goose]
dir = "./internal/database/migrations"

# [database "development"]
# driver = "postgres"
# dsn = "user=saniyhassan password=U1lNtin4kdRw dbname=webcms host=ep-twilight-rain-a519w3n4.us-east-2.aws.neon.tech port=5432 sslmode=disable"

[database]
driver = "postgres"
dsn = "user=saniyhassan password=U1lNtin4kdRw dbname=webcms host=ep-twilight-rain-a519w3n4.us-east-2.aws.neon.tech port=5432 sslmode=require"
