// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Invoice struct {
	ID            uuid.UUID     `json:"id"`
	TenantID      uuid.UUID     `json:"tenant_id"`
	UserID        uuid.NullUUID `json:"user_id"`
	CustomerEmail string        `json:"customer_email"`
	AmountCents   int32         `json:"amount_cents"`
	Currency      string        `json:"currency"`
	Status        string        `json:"status"`
	IssuedAt      time.Time     `json:"issued_at"`
	DueAt         sql.NullTime  `json:"due_at"`
}

type Payment struct {
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	InvoiceID      uuid.UUID      `json:"invoice_id"`
	AmountCents    int32          `json:"amount_cents"`
	Currency       string         `json:"currency"`
	Provider       string         `json:"provider"`
	Status         string         `json:"status"`
	TransactionRef sql.NullString `json:"transaction_ref"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PriceCents  int32          `json:"price_cents"`
	Currency    string         `json:"currency"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Domain    sql.NullString `json:"domain"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}
