// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CountTenantInvoices(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountTenantPayments(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountTenantProducts(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountTenantUsers(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteInvoice(ctx context.Context, id uuid.UUID) error
	DeletePayment(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error)
	GetInvoiceStatusSummary(ctx context.Context, tenantID uuid.UUID) ([]GetInvoiceStatusSummaryRow, error)
	GetInvoiceSummary(ctx context.Context, id uuid.UUID) (GetInvoiceSummaryRow, error)
	GetInvoiceWithPayments(ctx context.Context, arg GetInvoiceWithPaymentsParams) ([]GetInvoiceWithPaymentsRow, error)
	GetOutstandingInvoices(ctx context.Context, tenantID uuid.UUID) ([]GetOutstandingInvoicesRow, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentProviderSummary(ctx context.Context, tenantID uuid.UUID) ([]GetPaymentProviderSummaryRow, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetRevenueOverTime(ctx context.Context, tenantID uuid.UUID) ([]GetRevenueOverTimeRow, error)
	GetTenantByDomain(ctx context.Context, domain sql.NullString) (Tenant, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantRevenue(ctx context.Context, id uuid.UUID) (GetTenantRevenueRow, error)
	GetTopCustomers(ctx context.Context, arg GetTopCustomersParams) ([]GetTopCustomersRow, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListInvoicesByTenant(ctx context.Context, arg ListInvoicesByTenantParams) ([]Invoice, error)
	ListPaymentsByInvoice(ctx context.Context, arg ListPaymentsByInvoiceParams) ([]Payment, error)
	ListProductsByTenant(ctx context.Context, arg ListProductsByTenantParams) ([]Product, error)
	ListTenantProductsWithInvoices(ctx context.Context, arg ListTenantProductsWithInvoicesParams) ([]ListTenantProductsWithInvoicesRow, error)
	ListTenantUsersWithInvoices(ctx context.Context, arg ListTenantUsersWithInvoicesParams) ([]ListTenantUsersWithInvoicesRow, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]User, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
